name: Snyk

on: push

jobs:
  security:
    name: Security Scanning
    strategy:
      matrix:
        python: ['3.10']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Also fetch git-tags
      - name: Setup Snyk
        uses: snyk/actions/setup@master
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Snyk monitor
        run: |
          pip install -U wheel
          pip install .
          snyk test --file=setup.py --command=python3
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
