name: Lint and Unit Tests

on: [push]

jobs:
  nox:
    strategy:
      matrix:
        python: ['3.10']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Also fetch git-tags
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: nox
      env:
        GIT_REPO_NAME: "${GITHUB_REPOSITORY#*/}"
      run: |
        pip install .[ci]
        nox
